//Licensed under the ISC license.
//Copyright 2014 Yuki Ahmed

var jmap = require("../lib/jsonmap.js");

var schema = {
  "Time": null,
  "Global": null,
  "Japan": null,
  "North America": null,
  "Aegis": null,
  "Atomos": null,
  "Carbuncle": null,
  "Garuda": null,
  "Gungnir": null,
  "Kujata": null,
  "Ramuh": null,
  "Tonberry": null,
  "Typhon": null,
  "Unicorn": null,
  "Alexander": null,
  "Bahamut": null,
  "Durandal": null,
  "Fenrir": null,
  "Ifrit": null,
  "Ridill": null,
  "Tiamat": null,
  "Ultima": null,
  "Valefor": null,
  "Yojimbo": null,
  "Zeromus": null,
  "Anima": null,
  "Asura": null,
  "Belias": null,
  "Chocobo": null,
  "Hades": null,
  "Ixion": null,
  "Mandragora": null,
  "Masamune": null,
  "Pandaemonium": null,
  "Shinryu": null,
  "Titan": null,
  "Adamantoise": null,
  "Balmung": null,
  "Cactuar": null,
  "Coeurl": null,
  "Faerie": null,
  "Gilgamesh": null,
  "Goblin": null,
  "Jenova": null,
  "Mateus": null,
  "Midgardsormr": null,
  "Sargatanas": null,
  "Siren": null,
  "Zalera": null,
  "Behemoth": null,
  "Brynhildr": null,
  "Diabolos": null,
  "Excalibur": null,
  "Exodus": null,
  "Famfrit": null,
  "Hyperion": null,
  "Lamia": null,
  "Leviathan": null,
  "Malboro": null,
  "Ultros": null,
  "Cerberus": null,
  "Lich": null,
  "Moogle": null,
  "Odin": null,
  "Phoenix": null,
  "Ragnarok": null,
  "Shiva": null,
  "Zodiark": null
}

exports = module.exports = jmap(schema);
